# Generated by Django 5.2 on 2025-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0002_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(upload_to="manga_pages/"),
        ),
        migrations.AlterField(
            model_name="page",
            name="order",
            field=models.PositiveIntegerField(),
        ),
    ]
