# Generated by Django 5.2 on 2025-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewer", "0003_alter_page_options_page_slug_alter_page_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manga",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="cover",
        ),
        migrations.AlterField(
            model_name="manga",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
